-- Create Table PP_RCA_REASONS

DROP TABLE IF EXISTS PP_RCA_REASONS;
CREATE TABLE PP_RCA_REASONS AS (
SELECT DISTINCT
    CASES.MANDT
    ,CASES.AUFNR
    ,R1.PRED_VALUE AS PREDV
    ,R1.MAX1 AS REASN
    ,R1.PRETTY_NAMES1 AS REASN_PRETTY
    ,R1.MAX1_VALUE AS RSVAL
    ,ROUND(R1.MAX1_SHAP,4) AS RSHAP
    ,ROUND(R1.REASON_WEIGHT1,4) AS RWGHT
    ,1 AS RSNUM
FROM TMP_PP_AUFK_AFKO_AFPO AS CASES
JOIN (SELECT CASE_KEY,PRED_VALUE,MAX1,MAX1_VALUE,MAX1_SHAP,REASON_WEIGHT1,PRETTY_NAMES1 FROM RCA_REASONS) AS R1 ON 1=1
    AND CASES.AUFNR = R1.CASE_KEY

UNION ALL

SELECT 
    CASES.MANDT
    ,CASES.AUFNR
    ,R2.PRED_VALUE AS PREDV
    ,R2.MAX2 AS REASN
    ,R2.PRETTY_NAMES2 AS REASN_PRETTY
    ,R2.MAX2_VALUE AS RSVAL
    ,ROUND(R2.MAX2_SHAP,4) AS RSHAP
    ,ROUND(R2.REASON_WEIGHT2,4) AS RWGHT
    ,2 AS RSNUM
FROM TMP_PP_AUFK_AFKO_AFPO AS CASES
JOIN (SELECT CASE_KEY,PRED_VALUE,MAX2,MAX2_VALUE,MAX2_SHAP,REASON_WEIGHT2,PRETTY_NAMES2 FROM RCA_REASONS) AS R2 ON 2=2
    AND CASES.AUFNR = R2.CASE_KEY

UNION ALL

SELECT 
    CASES.MANDT
    ,CASES.AUFNR
    ,R3.PRED_VALUE AS PREDV
    ,R3.MAX3 AS REASN
    ,R3.PRETTY_NAMES3 AS REASN_PRETTY
    ,R3.MAX3_VALUE AS RSVAL
    ,ROUND(R3.MAX3_SHAP,4) AS RSHAP
    ,ROUND(R3.REASON_WEIGHT3,4) AS RWGHT
    ,3 AS RSNUM
FROM TMP_PP_AUFK_AFKO_AFPO AS CASES
JOIN (SELECT CASE_KEY,PRED_VALUE,MAX3,MAX3_VALUE,MAX3_SHAP,REASON_WEIGHT3,PRETTY_NAMES3 FROM RCA_REASONS) AS R3 ON 3=3
    AND CASES.AUFNR = R3.CASE_KEY

);